name: git_log_markdown_formatter
description: A sample command-line application with basic argument parsing.
version: 1.1.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.2

# Add regular dependencies here.
dependencies:
  args: ^2.4.2

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
