import 'dart:io';

void main() {
  var metaDartFile = File("bin/meta.dart");

  try {
    // Read the pubspec.yaml file
    final pubspecFile = File('pubspec.yaml');
    final pubspecContent = pubspecFile.readAsStringSync();

    // Use a regular expression to extract the version
    final versionMatch = RegExp(r'version: (.+)').firstMatch(pubspecContent);

    // Check if a match was found
    if (versionMatch != null) {
      final version = versionMatch.group(1)!;

      String metaDartFileContents = """
/// DO NOT EDIT THIS FILE EXCEPT TO ENTER INITIAL VERSION AND OTHER META INFO 
/// THIS FILE IS AUTOMATICALLY OVER WRITTEN BY MetaUpdate 

Map<String, String> meta = <String, String>{
  "version":"$version",
};
  """;

      metaDartFile.writeAsStringSync(metaDartFileContents);
    } else {
      print('Version not found in pubspec.yaml');
    }
  } catch (e) {
    print('Error: $e');
  }
}
