name: Release Workflow

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v1.6.2
      - name: Install GitHub CLI
        run: |
          sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-key C99B11DEB97541F0
          sudo apt-add-repository https://cli.github.com/packages
          sudo apt-get update
          sudo apt-get install gh

      - name: Verify GitHub CLI installation
        run: gh --version

      - name: Get Version from pubspec.yaml
        run: echo "::set-env name=PACKAGE_VERSION::$(dart get_version.dart)"
      
      - name: Build Executable
        run: dart compile exe bin/git_log_markdown_formatter.dart -o glmf

      - name: Upload Executable Artifact
        uses: actions/upload-artifact@v2
        with:
          name: glmf
          path: glmf

      - name: Publish Release
        run: |
          gh release create v${{ env.PACKAGE_VERSION }} \
            dist/my-binary.zip \
            -t "Release v${{ env.PACKAGE_VERSION }}" \
            -n "$(cat RELEASE_NOTES.md)"

      - name: Create Git Tag
        run: git tag v${{ env.PACKAGE_VERSION }} && git push origin v${{ env.PACKAGE_VERSION }}
