name: Release Workflow

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v1.6.2

      - name: Verify GitHub CLI installation
        run: gh --version
      
      - name: Build Executable
        run: |
          dart pub get
          dart compile exe bin/git_log_markdown_formatter.dart -o glmf
          zip glmf.zip glmf

      - name: Upload Executable Artifact
        uses: actions/upload-artifact@v2
        with:
          name: glmf
          path: glmf.zip

      - name: Publish Release
        run: |
          RELEASE_VERSION=$(dart get_version.dart)
       
          gh release create $RELEASE_VERSION \
            glmf.zip \
            -t "Release $RELEASE_VERSION" \
            -n "Release $RELEASE_VERSION"
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Create Git Tag
        run: |
          RELEASE_VERSION=$(dart get_version.dart)
          git tag $RELEASE_VERSION && git push origin $RELEASE_VERSION
